"""Fail-closed clock-skew guard for distributed Git write-lock leases."""

from __future__ import annotations

import logging
from datetime import datetime, timedelta
from typing import Any, Dict

logger = logging.getLogger(__name__)

# A remote lease is intentionally kept authoritative for this extra interval
# after its wall-clock expiry. This protects multi-PC WRITE mode from a client
# whose Windows clock is ahead of the lock owner's clock. Safety is preferred
# over fast stale-lock recovery; administrative force-release remains available.
DEFAULT_CLOCK_SKEW_TOLERANCE_SECONDS = 10 * 60


def install_lock_clock_skew_guard(
    provider_cls: Any,
    tolerance_seconds: int = DEFAULT_CLOCK_SKEW_TOLERANCE_SECONDS,
) -> None:
    """Treat recently expired remote leases as valid for a skew grace period.

    The underlying provider uses an absolute ``lease_expires_at`` generated by
    the lock owner's wall clock. A second PC with a clock that is ahead can
    otherwise declare a fresh lock stale immediately. This wrapper fails closed:
    when the normal lease check reports expired, the same lock remains valid
    until ``lease_expires_at + tolerance``.

    The wrapper does not change ownership/CAS semantics and does not permit a
    client to overwrite a live remote lock. Locks older than the tolerance are
    still stale and can be acquired through the existing atomic path.
    """
    if getattr(provider_cls, "_clock_skew_guard_installed", False):
        return

    tolerance_seconds = max(0, int(tolerance_seconds))
    original_is_lock_valid = provider_cls._is_lock_valid

    def is_lock_valid_with_clock_skew_guard(self, lock_data: Dict[str, Any]) -> bool:
        if original_is_lock_valid(self, lock_data):
            return True
        if not lock_data.get("locked", False):
            return False

        lease_expires_at = lock_data.get("lease_expires_at")
        if not lease_expires_at:
            return False

        try:
            expires = datetime.fromisoformat(str(lease_expires_at))
            grace_deadline = expires + timedelta(seconds=tolerance_seconds)
            if datetime.now() < grace_deadline:
                logger.warning(
                    "Remote write lock is past local lease time but inside the "
                    "clock-skew safety window; keeping lock authoritative"
                )
                return True
        except (TypeError, ValueError, OverflowError):
            return False

        return False

    provider_cls._is_lock_valid = is_lock_valid_with_clock_skew_guard
    provider_cls._clock_skew_guard_installed = True
    provider_cls._clock_skew_tolerance_seconds = tolerance_seconds
