# -*- coding: utf-8 -*-
"""Destination-bound provisioning for workstation Git and database secrets.

Legacy Git-only v1 bundles remain readable. New workstation v2 bundles carry
both the Git configuration and the *existing* shared SQLCipher workspace key.
The workspace key is never generated by this module.
"""

import base64
import json
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Optional, Tuple

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import padding, rsa
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

from centermanager.core.secret_store import protect_secret, unprotect_secret
from centermanager.database.encryption import DatabaseKeyStore, DatabaseKeyUnavailable

_REQUEST_FORMAT = "CenterManager-Git-Provisioning-Request:v1"
_BUNDLE_FORMAT_V1 = "CenterManager-Git-Provisioning-Bundle:v1"
_BUNDLE_FORMAT_V2 = "CenterManager-Workstation-Provisioning-Bundle:v2"
_PAYLOAD_FORMAT_V2 = "CenterManager-Workstation-Provisioning-Payload:v2"
_PRIVATE_KEY_FILE = "git_provisioning_private.json"
_WORKSPACE_KEY_BYTES = 32


class ProvisioningError(ValueError):
    pass


@dataclass(frozen=True)
class ProvisioningPaths:
    private_key_file: Path


def _b64e(value: bytes) -> str:
    return base64.b64encode(value).decode("ascii")


def _b64d(value: str) -> bytes:
    try:
        return base64.b64decode(value, validate=True)
    except Exception as exc:
        raise ProvisioningError("Invalid provisioning base64 payload") from exc


def _paths(config_path: Path) -> ProvisioningPaths:
    return ProvisioningPaths(private_key_file=config_path.parent / _PRIVATE_KEY_FILE)


def _unprotect_private(record: Dict[str, Any]):
    protected = record.get("protected_private_key")
    if not isinstance(protected, str):
        raise ProvisioningError("Destination provisioning identity is invalid")
    if protected.startswith("DPAPI:v2:"):
        private_pem = unprotect_secret(protected)
    elif protected.startswith("TEST:v1:"):
        private_pem = _b64d(protected[8:]).decode("utf-8")
    else:
        raise ProvisioningError("Unsupported destination private-key protection")
    return serialization.load_pem_private_key(private_pem.encode("ascii"), password=None)


def _new_identity(paths: ProvisioningPaths) -> Dict[str, Any]:
    private_key = rsa.generate_private_key(public_exponent=65537, key_size=3072)
    private_pem = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    ).decode("ascii")
    public_pem = private_key.public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    ).decode("ascii")
    protected_private = (
        protect_secret(private_pem)
        if os.name == "nt"
        else "TEST:v1:" + _b64e(private_pem.encode("utf-8"))
    )
    record = {
        "format": _REQUEST_FORMAT,
        "public_key": public_pem,
        "protected_private_key": protected_private,
    }
    paths.private_key_file.write_text(json.dumps(record, indent=2), encoding="utf-8")
    return record


def ensure_destination_request(config_path: Path) -> Dict[str, Any]:
    """Return this Windows identity's public request, creating a key if needed.

    A copied DPAPI-protected private key is intentionally unusable on another
    Windows identity. In that case it is replaced with a fresh destination key.
    """
    paths = _paths(config_path)
    paths.private_key_file.parent.mkdir(parents=True, exist_ok=True)
    record = None
    if paths.private_key_file.exists():
        try:
            candidate = json.loads(paths.private_key_file.read_text(encoding="utf-8"))
            _unprotect_private(candidate)
            public_pem = candidate.get("public_key")
            if isinstance(public_pem, str) and public_pem:
                record = candidate
        except Exception:
            record = None
    if record is None:
        record = _new_identity(paths)
    return {"format": _REQUEST_FORMAT, "public_key": record["public_key"]}


def write_destination_request(config_path: Path, output_path: Path) -> None:
    output_path.write_text(
        json.dumps(ensure_destination_request(config_path), indent=2), encoding="utf-8"
    )


def build_workstation_payload(git_payload: Dict[str, Any], workspace_key: bytes) -> Dict[str, Any]:
    """Build a v2 payload using an already-provisioned shared workspace key."""
    if not isinstance(git_payload, dict):
        raise ProvisioningError("Git provisioning payload has invalid type")
    if not isinstance(workspace_key, bytes) or len(workspace_key) != _WORKSPACE_KEY_BYTES:
        raise ProvisioningError("Workspace database key must be exactly 256 bits")
    return {
        "format": _PAYLOAD_FORMAT_V2,
        "git": dict(git_payload),
        "workspace_database_key": _b64e(workspace_key),
    }


def parse_provisioning_payload(payload: Dict[str, Any]) -> Tuple[Dict[str, Any], Optional[bytes]]:
    """Return ``(git_payload, workspace_key)`` for v1 or v2 payloads."""
    if not isinstance(payload, dict):
        raise ProvisioningError("Provisioning payload has invalid type")
    if payload.get("format") != _PAYLOAD_FORMAT_V2:
        # Legacy v1 payloads are flat GitConfig dictionaries.
        return payload, None

    git_payload = payload.get("git")
    encoded_key = payload.get("workspace_database_key")
    if not isinstance(git_payload, dict):
        raise ProvisioningError("Workstation provisioning payload has invalid Git configuration")
    if not isinstance(encoded_key, str):
        raise ProvisioningError("Workstation provisioning payload has no database key")
    workspace_key = _b64d(encoded_key)
    if len(workspace_key) != _WORKSPACE_KEY_BYTES:
        raise ProvisioningError("Workspace database key must be exactly 256 bits")
    return git_payload, workspace_key


def provision_workspace_database_key(
    workspace_key: bytes,
    *,
    key_store: Optional[DatabaseKeyStore] = None,
) -> None:
    """Re-wrap the shared key for this destination without changing its value.

    A valid local key with a different value is never overwritten. A missing or
    unusable (for example copied foreign-DPAPI) local bundle may be replaced only
    after the caller has authenticated/decrypted a destination-bound bundle.
    """
    if not isinstance(workspace_key, bytes) or len(workspace_key) != _WORKSPACE_KEY_BYTES:
        raise ProvisioningError("Workspace database key must be exactly 256 bits")
    store = key_store or DatabaseKeyStore()

    if store.bundle_path.is_file():
        try:
            existing = store.load()
        except DatabaseKeyUnavailable:
            try:
                store.provision(workspace_key, overwrite=True)
            except DatabaseKeyUnavailable as exc:
                raise ProvisioningError("Could not provision the workspace database key") from exc
        else:
            if existing != workspace_key:
                raise ProvisioningError(
                    "A different valid workspace database key is already provisioned; refusing to overwrite it"
                )
            return
    else:
        try:
            store.provision(workspace_key)
        except DatabaseKeyUnavailable as exc:
            raise ProvisioningError("Could not provision the workspace database key") from exc

    try:
        persisted = store.load()
    except DatabaseKeyUnavailable as exc:
        raise ProvisioningError("Provisioned workspace database key could not be reloaded") from exc
    if persisted != workspace_key:
        raise ProvisioningError("Provisioned workspace database key verification failed")


def create_bundle(
    request: Dict[str, Any],
    payload: Dict[str, Any],
    *,
    bundle_format: Optional[str] = None,
) -> Dict[str, Any]:
    """Encrypt a provisioning payload to one destination public key.

    Flat legacy Git payloads default to v1. Workstation payloads created by
    :func:`build_workstation_payload` default to v2.
    """
    if request.get("format") != _REQUEST_FORMAT:
        raise ProvisioningError("Unsupported provisioning request format")
    public_pem = request.get("public_key")
    if not isinstance(public_pem, str) or not public_pem:
        raise ProvisioningError("Provisioning request has no public key")
    try:
        public_key = serialization.load_pem_public_key(public_pem.encode("ascii"))
    except Exception as exc:
        raise ProvisioningError("Invalid destination public key") from exc

    if bundle_format is None:
        bundle_format = (
            _BUNDLE_FORMAT_V2
            if payload.get("format") == _PAYLOAD_FORMAT_V2
            else _BUNDLE_FORMAT_V1
        )
    if bundle_format not in {_BUNDLE_FORMAT_V1, _BUNDLE_FORMAT_V2}:
        raise ProvisioningError("Unsupported provisioning bundle format")

    aes_key = AESGCM.generate_key(bit_length=256)
    nonce = os.urandom(12)
    plaintext = json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    ciphertext = AESGCM(aes_key).encrypt(nonce, plaintext, bundle_format.encode("ascii"))
    wrapped_key = public_key.encrypt(
        aes_key,
        padding.OAEP(
            mgf=padding.MGF1(algorithm=hashes.SHA256()),
            algorithm=hashes.SHA256(),
            label=None,
        ),
    )
    return {
        "format": bundle_format,
        "wrapped_key": _b64e(wrapped_key),
        "nonce": _b64e(nonce),
        "ciphertext": _b64e(ciphertext),
    }


def decrypt_bundle(config_path: Path, bundle: Dict[str, Any]) -> Dict[str, Any]:
    """Open a v1/v2 bundle using this destination's protected private key."""
    bundle_format = bundle.get("format")
    if bundle_format not in {_BUNDLE_FORMAT_V1, _BUNDLE_FORMAT_V2}:
        raise ProvisioningError("Unsupported provisioning bundle format")
    paths = _paths(config_path)
    if not paths.private_key_file.exists():
        raise ProvisioningError("This machine has no provisioning identity")
    try:
        record = json.loads(paths.private_key_file.read_text(encoding="utf-8"))
        private_key = _unprotect_private(record)
        aes_key = private_key.decrypt(
            _b64d(bundle["wrapped_key"]),
            padding.OAEP(
                mgf=padding.MGF1(algorithm=hashes.SHA256()),
                algorithm=hashes.SHA256(),
                label=None,
            ),
        )
        plaintext = AESGCM(aes_key).decrypt(
            _b64d(bundle["nonce"]),
            _b64d(bundle["ciphertext"]),
            bundle_format.encode("ascii"),
        )
        payload = json.loads(plaintext.decode("utf-8"))
    except ProvisioningError:
        raise
    except Exception as exc:
        raise ProvisioningError(
            "Provisioning bundle is invalid or belongs to another destination"
        ) from exc
    if not isinstance(payload, dict):
        raise ProvisioningError("Provisioning payload has invalid type")
    return payload
