# -*- coding: utf-8 -*-
"""CenterManager Design System public API."""

from .tokens import (
    TOKEN_SCHEMA_VERSION,
    BADGE_COLORS,
    BORDER_RADIUS,
    COLORS,
    COMPONENT_METRICS,
    CONTROL_SIZES,
    ELEVATION,
    FONT_FAMILY,
    FONT_WEIGHTS,
    RADIUS,
    SHADOWS,
    SPACING,
    STATES,
    TYPOGRAPHY,
)
from .theme import DEFAULT_THEME, DesignTheme, theme
from .foundation import (
    Badge,
    BadgeTone,
    Button,
    ButtonVariant,
    Card,
    ComponentSize,
    Dialog,
    EmptyState,
    ErrorState,
    Input,
    LoadingState,
    Select,
    Skeleton,
    StateView,
    Tabs,
    Toolbar,
)
from .components import (
    ActivityCard,
    Avatar,
    Breadcrumb,
    DangerButton,
    FilterBar,
    InfoCard,
    InfoPanel,
    PrimaryButton,
    SearchBar,
    SecondaryButton,
    SectionHeader,
    StatisticCard,
    StatusBadge,
)

__all__ = [
    "TOKEN_SCHEMA_VERSION",
    "COLORS",
    "FONT_FAMILY",
    "FONT_WEIGHTS",
    "TYPOGRAPHY",
    "SPACING",
    "RADIUS",
    "BORDER_RADIUS",
    "ELEVATION",
    "SHADOWS",
    "STATES",
    "CONTROL_SIZES",
    "COMPONENT_METRICS",
    "BADGE_COLORS",
    "DesignTheme",
    "DEFAULT_THEME",
    "theme",
    # Component Foundation V2
    "ComponentSize",
    "ButtonVariant",
    "BadgeTone",
    "Button",
    "Input",
    "Select",
    "Badge",
    "Card",
    "Toolbar",
    "Tabs",
    "Dialog",
    "Skeleton",
    "StateView",
    "EmptyState",
    "LoadingState",
    "ErrorState",
    # Legacy component exports retained until workspace migration.
    "StatisticCard",
    "InfoCard",
    "ActivityCard",
    "SectionHeader",
    "StatusBadge",
    "Avatar",
    "PrimaryButton",
    "SecondaryButton",
    "DangerButton",
    "SearchBar",
    "Breadcrumb",
    "FilterBar",
    "InfoPanel",
]
